FROM node:18 AS base
WORKDIR /app
# RUN npm i -g pnpm
# COPY package.json pnpm-lock.yaml ./
COPY package.json package-lock.json ./
RUN npm install npm -g
RUN npm install


COPY . .
RUN npm run build

FROM node:18-alpine3.19 as release
WORKDIR /app
# RUN npm i -g pnpm

COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package.json ./package.json
COPY --from=base /app/.next ./.next

EXPOSE 3000

CMD ["npm", "start"]